version: '3.8'

services:
  web:
    build: .
    container_name: webgrup8
    ports:
      - "80:80"
    volumes:
      - /home/devops08/codi:/var/www/html
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
